create table Account (
	ID INT,
	name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	country VARCHAR(50),
	date_of_birth DATE,
	is_host VARCHAR(50)
);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (1, 'Lena Reford', 'lreford0@homestead.com', 'Female', 'Colombia', '1958-11-01', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (2, 'Brendon Olman', 'bolman1@ezinearticles.com', 'Male', 'Indonesia', '1960-06-15', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (3, 'Del Barczynski', 'dbarczynski2@geocities.com', 'Female', 'Brazil', '1964-06-03', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (4, 'Eolanda Phonix', 'ephonix3@a8.net', 'Female', 'Thailand', '1950-02-12', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (5, 'Vachel Borthram', 'vborthram4@pagesperso-orange.fr', 'Male', 'China', '1937-04-04', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (6, 'Zechariah Pardew', 'zpardew5@about.com', 'Male', 'China', '1984-05-17', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (7, 'Giffard Brownhall', 'gbrownhall6@trellian.com', 'Male', 'China', '1959-01-08', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (8, 'Barry Cheyne', 'bcheyne7@cmu.edu', 'Male', 'Czech Republic', '1995-02-06', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (9, 'Sven Tarpey', 'starpey8@netscape.com', 'Male', 'Mauritania', '1981-06-21', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (10, 'Katha Mostin', 'kmostin9@gov.uk', 'Female', 'China', '1935-04-08', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (11, 'Isadore Tirrell', 'itirrella@tumblr.com', 'Male', 'China', '1968-06-05', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (12, 'Helli Worham', 'hworhamb@hao123.com', 'Female', 'Philippines', '1967-10-30', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (13, 'Mavra Thyng', 'mthyngc@dagondesign.com', 'Female', 'China', '1999-02-19', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (14, 'Tierney Gingles', 'tginglesd@homestead.com', 'Female', 'Poland', '1944-08-14', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (15, 'Travus Elvin', 'telvine@icio.us', 'Male', 'Russia', '1939-02-04', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (16, 'Raymund Bicker', 'rbickerf@psu.edu', 'Male', 'Russia', '1972-09-19', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (17, 'Ranique Sayre', 'rsayreg@pen.io', 'Female', 'Ireland', '1923-10-09', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (18, 'Winnie Molineux', 'wmolineuxh@tripod.com', 'Male', 'Russia', '1999-08-21', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (19, 'Brnaby Smullen', 'bsmulleni@google.cn', 'Male', 'Portugal', '1970-02-06', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (20, 'Pieter Leyrroyd', 'pleyrroydj@seattletimes.com', 'Male', 'Latvia', '1953-08-03', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (21, 'Zechariah Parkinson', 'zparkinsonk@alibaba.com', 'Male', 'Indonesia', '1924-11-17', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (22, 'Stepha Ibarra', 'sibarral@hugedomains.com', 'Female', 'China', '1987-01-25', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (23, 'Lorain Fazakerley', 'lfazakerleym@over-blog.com', 'Female', 'China', '1948-01-16', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (24, 'Rockey Kowalik', 'rkowalikn@seesaa.net', 'Male', 'China', '1928-11-05', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (25, 'Garland Braferton', 'gbrafertono@usgs.gov', 'Female', 'Venezuela', '1970-03-23', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (26, 'Rickey Rosekilly', 'rrosekillyp@earthlink.net', 'Male', 'Philippines', '1925-12-17', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (27, 'Filide Merryweather', 'fmerryweatherq@ihg.com', 'Female', 'Zambia', '1943-11-02', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (28, 'Wynnie Tebboth', 'wtebbothr@indiatimes.com', 'Female', 'Philippines', '1990-10-14', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (29, 'Tildi Lars', 'tlarss@smh.com.au', 'Female', 'Ivory Coast', '1990-12-29', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (30, 'Gretel Jiranek', 'gjiranekt@mlb.com', 'Female', 'China', '1965-07-21', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (31, 'Vinnie Pedrollo', 'vpedrollou@buzzfeed.com', 'Male', 'Albania', '1964-05-24', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (32, 'Heidie Arnall', 'harnallv@360.cn', 'Female', 'Malaysia', '1951-09-04', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (33, 'Lonni Leither', 'lleitherw@skype.com', 'Female', 'China', '1992-04-24', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (34, 'Sissie Hughson', 'shughsonx@nasa.gov', 'Female', 'Philippines', '1948-06-16', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (35, 'Lilly Standish', 'lstandishy@dropbox.com', 'Female', 'Philippines', '1952-06-10', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (36, 'Chastity Elks', 'celksz@archive.org', 'Female', 'Poland', '2001-10-23', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (37, 'Boyd Rosenwasser', 'brosenwasser10@cisco.com', 'Male', 'Dominican Republic', '1937-03-11', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (38, 'Lennie Bilbey', 'lbilbey11@scribd.com', 'Male', 'Russia', '1957-04-27', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (39, 'Braden Tattershaw', 'btattershaw12@alexa.com', 'Male', 'Denmark', '1980-02-26', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (40, 'Charmane Cauderlie', 'ccauderlie13@washington.edu', 'Female', 'Japan', '1923-08-28', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (41, 'Trude Paszak', 'tpaszak14@ocn.ne.jp', 'Female', 'Argentina', '1996-01-25', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (42, 'Morie Alekseicik', 'malekseicik15@pcworld.com', 'Male', 'Nigeria', '1993-03-01', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (43, 'Ronny Shotboulte', 'rshotboulte16@examiner.com', 'Female', 'Nigeria', '1979-10-13', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (44, 'Massimiliano Becke', 'mbecke17@oracle.com', 'Male', 'Indonesia', '1970-03-23', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (45, 'Robenia Yarnold', 'ryarnold18@constantcontact.com', 'Female', 'Afghanistan', '1927-06-04', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (46, 'Joel Sacase', 'jsacase19@time.com', 'Male', 'France', '1993-03-22', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (47, 'Myrah MacGille', 'mmacgille1a@lycos.com', 'Female', 'Ukraine', '1999-12-21', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (48, 'Guilbert Phillis', 'gphillis1b@unesco.org', 'Male', 'Indonesia', '1934-10-05', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (49, 'Kearney Woodham', 'kwoodham1c@ezinearticles.com', 'Male', 'Azerbaijan', '1963-09-08', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (50, 'Prinz Joselson', 'pjoselson1d@cloudflare.com', 'Male', 'Philippines', '1970-01-27', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (51, 'Paulie Adshede', 'padshede1e@rambler.ru', 'Female', 'Indonesia', '1992-05-02', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (52, 'Patsy Staziker', 'pstaziker1f@flickr.com', 'Female', 'Russia', '1980-02-19', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (53, 'Maryellen Smallpeace', 'msmallpeace1g@patch.com', 'Female', 'Colombia', '1994-04-12', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (54, 'Otis Jarvie', 'ojarvie1h@a8.net', 'Male', 'Colombia', '1984-09-07', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (55, 'Pippo Hurkett', 'phurkett1i@kickstarter.com', 'Male', 'China', '1995-10-07', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (56, 'Claus Runnalls', 'crunnalls1j@vistaprint.com', 'Male', 'Portugal', '1934-09-17', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (57, 'Evanne Gillbanks', 'egillbanks1k@amazon.com', 'Female', 'Cuba', '1991-11-10', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (58, 'Lynn Bettam', 'lbettam1l@cnbc.com', 'Female', 'Norway', '1941-11-20', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (59, 'Kerwin Iglesias', 'kiglesias1m@posterous.com', 'Male', 'China', '1921-01-13', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (60, 'Alfie Loukes', 'aloukes1n@spotify.com', 'Male', 'Indonesia', '1964-06-13', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (61, 'Ad Dugald', 'adugald1o@reverbnation.com', 'Male', 'Nigeria', '1933-12-24', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (62, 'Adele Scadding', 'ascadding1p@unicef.org', 'Female', 'Russia', '1963-08-24', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (63, 'Lief Fidell', 'lfidell1q@edublogs.org', 'Male', 'Pakistan', '1980-05-20', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (64, 'Avie Cowl', 'acowl1r@miibeian.gov.cn', 'Female', 'Indonesia', '1951-06-28', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (65, 'Birch Gayler', 'bgayler1s@nytimes.com', 'Male', 'Croatia', '1941-09-09', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (66, 'Fons Pain', 'fpain1t@4shared.com', 'Male', 'China', '1952-03-01', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (67, 'Hersh Magne', 'hmagne1u@reference.com', 'Male', 'Vietnam', '1937-10-18', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (68, 'Koralle Braksper', 'kbraksper1v@kickstarter.com', 'Female', 'China', '1996-04-22', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (69, 'Riane Rubega', 'rrubega1w@paginegialle.it', 'Female', 'Russia', '1979-01-18', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (70, 'Mark Chaize', 'mchaize1x@phpbb.com', 'Male', 'Japan', '1987-07-25', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (71, 'Isaac Standbridge', 'istandbridge1y@netvibes.com', 'Male', 'Sweden', '1923-05-20', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (72, 'Adela Donan', 'adonan1z@sogou.com', 'Female', 'China', '1946-05-21', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (73, 'Floria Henningham', 'fhenningham20@yandex.ru', 'Female', 'Poland', '1972-10-04', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (74, 'Marlon Keveren', 'mkeveren21@bbb.org', 'Male', 'Indonesia', '1950-10-03', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (75, 'Fernande Torres', 'ftorres22@webnode.com', 'Female', 'Laos', '1925-03-09', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (76, 'Winslow Chilver', 'wchilver23@si.edu', 'Male', 'Brazil', '1920-04-30', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (77, 'Michaelina Christofol', 'mchristofol24@fastcompany.com', 'Female', 'South Korea', '1969-06-10', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (78, 'Tiffy Dallon', 'tdallon25@who.int', 'Female', 'China', '1970-11-20', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (79, 'Jocelin Bowker', 'jbowker26@sphinn.com', 'Female', 'Peru', '1940-12-11', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (80, 'Tomlin Farnish', 'tfarnish27@opera.com', 'Male', 'France', '1942-10-17', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (81, 'Norina Dowyer', 'ndowyer28@unblog.fr', 'Female', 'Syria', '1968-02-17', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (82, 'Juan Scoon', 'jscoon29@opensource.org', 'Male', 'Nigeria', '1975-04-18', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (83, 'Dominik Keyson', 'dkeyson2a@ox.ac.uk', 'Male', 'China', '1971-11-10', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (84, 'Rosina Wison', 'rwison2b@oakley.com', 'Female', 'Indonesia', '1969-01-13', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (85, 'Elijah Bream', 'ebream2c@stumbleupon.com', 'Male', 'United Arab Emirates', '1948-01-06', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (86, 'Murial Novakovic', 'mnovakovic2d@fastcompany.com', 'Female', 'Serbia', '1958-11-25', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (87, 'Evita Hullock', 'ehullock2e@flavors.me', 'Female', 'Jordan', '1940-05-17', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (88, 'Katina Chastanet', 'kchastanet2f@wikispaces.com', 'Female', 'Mongolia', '1950-08-18', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (89, 'Tallie Milbank', 'tmilbank2g@abc.net.au', 'Female', 'Indonesia', '1920-08-27', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (90, 'Lyman De Vaan', 'lde2h@spiegel.de', 'Male', 'Brazil', '1985-05-28', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (91, 'Eydie Halahan', 'ehalahan2i@vkontakte.ru', 'Female', 'Indonesia', '1935-05-08', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (92, 'Uta Seabourne', 'useabourne2j@yellowbook.com', 'Female', 'Switzerland', '1935-11-02', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (93, 'Quintus Mordan', 'qmordan2k@economist.com', 'Male', 'China', '1964-06-16', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (94, 'Courtney Phelipeau', 'cphelipeau2l@youtu.be', 'Male', 'China', '1944-12-22', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (95, 'Adolf Lambrook', 'alambrook2m@reddit.com', 'Male', 'United States', '1973-04-12', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (96, 'Gordan Whates', 'gwhates2n@merriam-webster.com', 'Male', 'China', '1994-11-06', true);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (97, 'Rhody Lathleiff', 'rlathleiff2o@storify.com', 'Female', 'Indonesia', '1960-12-07', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (98, 'Natty Dickinson', 'ndickinson2p@patch.com', 'Male', 'China', '1988-08-29', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (99, 'Elsworth Godain', 'egodain2q@mayoclinic.com', 'Male', 'Jordan', '1939-11-01', false);
insert into Account (ID, name, email, gender, country, date_of_birth, is_host) values (100, 'Eadith Jenks', 'ejenks2r@businesswire.com', 'Female', 'Germany', '1954-08-11', false);
